### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Arkosee** [MaDHouSe79/mh-blackmarket#1]
Works awesome :) love it!

What do you think about removing the blips and making a minigame to get the location?

1. For example; Go to X spot, hack or do some form of minigame that requires an item or two
2. On success get sent a text message (or email) with a GPS coord that you can click to set a waypoint on that the ped spawns at
3. Go to said waypoint and find the ped

Could also have it similar to how it is with the ability to set multiple locations but randomize them.. So the location is randomly chosen from that array of coords so it's kind of random which spot he'll spawn in on the successful hacking/minigame completion

**Comment by MaDHouSe79** [comment]
for the multi shops, you can do that already, `Config.Shops = {}` there are 3 at the monent but 2 are disable, for items `Config.Items = {}` you can give every shop it's own items if you want, for the blips you can turn it off in the config, and a mission to get it, i can see what i can do with that :)

**Comment by Arkosee** [comment]
> for the multi shops, you can do that already, `Config.Shops = {}` there are 3 at the monent but 2 are disable, for items `Config.Items = {}` you can give every shop it's own items if you want, for the blips you can turn it off in the config, and a mission to get it, i can see what i can do with that :)

Yeah I saw that, I was more meaning maybe tie it into the minigame..

So say you have like 4 shops set up.. None are obviously "spawned" by default.. So when someone completes the minigame.. They get set to 1 of those 4 shops..

That way the blackmarket "rotates" persay and isn't in the same spot every single time.

Or I suppose an easier way to do that if you didn't want to include a minigame to get the location.. You could just have it pick a random location out of those configured on each resource start.. Which would make it rotate each server restart
